services:
  - type: web
    name: sentiment-trade-backend
    runtime: python
    repo: https://github.com/Dhara006/sentiment-trade
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FINNHUB_API_KEY
        sync: false
      - key: GNEWS_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false

  - type: web
    name: sentiment-trade-frontend
    runtime: python
    repo: https://github.com/Dhara006/sentiment-trade
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://sentiment-trade-backend.onrender.com
